#------------------------------------------------------------------------------
# TravisCI configuration file for solidity.
#
# The documentation for solidity is hosted at:
#
# http://solidity.readthedocs.org
#
# TODO - Re-add Sphinx validation which was in this file until removed in
# https://github.com/ethereum/solidity/commit/7cfd4d62e4f6dcea0ea3722f5ba4c6562674ba29.
#
# TODO - Merge with .travis.yml file which currently lives in the root of
# webthree-umbrella, but actually contains the automation for the Solidity
# Emscripten build, which will also need consolidating into here somehow.
#
# See https://github.com/ethereum/webthree-umbrella/blob/develop/.travis.yml
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
cache: ccache
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=Debug
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
        - os: osx
          osx_image: xcode7.1
          env: TRAVIS_BUILD_TYPE=Debug
        - os: osx
          osx_image: xcode7.1
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=Debug
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
git:
    depth: 2
before_install:
    - ./install_dependencies.sh
script:
    - ./fetch_umbrella_build_and_test.sh
