#------------------------------------------------------------------------------
# TravisCI configuration file for solidity.
#
# The documentation for solidity is hosted at:
#
# http://solidity.readthedocs.org
#
# TODO - Merge with .travis.yml file which currently lives in the root of
# webthree-umbrella, but actually contains the automation for the Solidity
# Emscripten build, which will also need consolidating into here somehow.
#
# See https://github.com/ethereum/webthree-umbrella/blob/develop/.travis.yml
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
branches:
    except:
        - /solidity-develop-windows-v[0-9]/
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=Debug
        - os: osx
          osx_image: xcode7.1
          env: TRAVIS_BUILD_TYPE=Debug
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=Debug
cache:
    - ccache
git:
    depth: 2
before_install:
    - ./install_deps.sh
before_script:
    - cd ..
    - git clone https://github.com/ethereum/tests.git
    - export ETHEREUM_TEST_PATH=$(pwd)/tests/
    - cd solidity
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$TRAVIS_BUILD_TYPE
script:
    # Build the code
    - make -j2

    # Run the tests
    - ETH_PATH_linux="eth"
    - ETH_PATH_osx="~/ethbin/eth"
    - ETH_PATH=$(ETH_PATH_$(TRAVIS_OS_NAME))
    #- $ETH_PATH --test -d /tmp/test
    #- while [ ! -S /tmp/test/geth.ipc ]; do sleep 2; done
    #- ./test/soltest --ipc /tmp/test/geth.ipc
    #- pkill eth

    # Generate Sphinx documentation if we're running on Trusty.
    #- $DOCS_COMMAND

    # -j is "junk paths", because we don't want any directory substructure in the output ZIP.
    - zip -j solidity-develop-$TRAVIS_OS_NAME.zip lllc/lllc solc/solc libdevcore/*.dylib libdevcore/*.so libevmasm/*.dylib libevmasm/*.so libsolidity/*.dylib libsolidity/*.so test/soltest
deploy:
    provider: releases
    api_key:
        secure: mGeDrlCbhPNQVqrk5wSqFZe/7C5HUIBWcZECJcFrEldN6ELj3a8mhDX9EWebidyFmZsf3ipKVMycJtXZHlH2kVZ0nZdRulq4bYhLiUFRaFQCHMW35dml5mxO/FPp+jhhZaylDUx+cI6AULbj8DvNFqSCfjx8qimRhJjRY4JHeG71N6g5+LU2/dA01D4Y97BUbQ5dYcmEyuEsriSpXOElIQIIv3+Q6MJNnLzxUA6EXsp4Qt3Qf3R1+EkI/RWOPbQsddpFNJBcBNOscCUFSZV3+ZK9E2RyHbPaL+Da4aJKVpgD7X1TFudq4PClMUTkg8CuJh/kvy9wkpaWyYHbLGQqu1vQ+NQ+vlTAKf8U+1xhC1IkX6nA+g4TlRksZRltRhpkBPnFoaQQGjD9eYyT1V/Htrn8Y/VGbYPBVa0GcEYXG5pDCBPz91RBpYwDcyUg9DEPNI6zYfQY8jA8xqtFwPX79Y22MDXIKhBskK00geuzh7Npy5Rnh4fLqVKMlffvYx3kwp444EFWtQ5jxbRCym2Th6EldkOM8Kble1JvixQtVb4s+DpTuwHCTrXZhwMuJpmwgRx52zyIsGrBPF3MOmdlwl+l0TD8UEJXt0JM1XSF1AROyYwXKDZQ9Qt4sd9ZKSWWaLJMEJf4kkZWYgTEI/FhOWlfshQCt8Z9S9r4fq2ywoo=
    file: solidity-develop-$TRAVIS_OS_NAME.zip
    skip_cleanup: true
    on:
        repo: bobsummerwill/solidity
        branch: standalone_prior_to_splat
