#------------------------------------------------------------------------------
# TravisCI configuration file for solidity.
#
# The documentation for solidity is hosted at:
#
# http://solidity.readthedocs.org
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode7.1
        - os: osx
          osx_image: xcode7.3
before_install:
    - ./setup.sh
before_script:
    - mkdir build
    - cd build
    - cmake ..
script:
    - make
