#------------------------------------------------------------------------------
# TravisCI configuration file for solidity.
#
# The documentation for solidity is hosted at:
#
# http://solidity.readthedocs.org
#
# TODO - Merge with .travis.yml file which currently lives in the root of
# webthree-umbrella, but actually contains the automation for the Solidity
# Emscripten build, which will also need consolidating into here somehow.
#
# See https://github.com/ethereum/webthree-umbrella/blob/develop/.travis.yml
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
cache: ccache
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=Debug
          env: CMAKE_OPTIONS="-DCMAKE_C_COMPILER=/usr/lib/ccache/$CC -DCMAKE_CXX_COMPILER=/usr/lib/ccache/$CXX"
          env: ETH_PATH="eth"
          env: DOCS_COMMAND="cd docs && sphinx-build -nW -b html -d _build/doctrees . _build/html && cd .."
        - os: osx
          osx_image: xcode7.1
          env: TRAVIS_BUILD_TYPE=Debug
          env: CMAKE_OPTIONS="-DCMAKE_C_COMPILER=/usr/lib/ccache/$CC -DCMAKE_CXX_COMPILER=/usr/lib/ccache/$CXX"
          env: ETH_PATH="~/ethbin/eth"
          env: DOCS_COMMAND=""
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=Debug
          env: CMAKE_OPTIONS=""
          env: ETH_PATH="~/ethbin/eth"
          env: DOCS_COMMAND=""
git:
    depth: 2
branches:
    except:
        - /solidity-appveyor-v[0-9]/
before_install:
    - ./install_deps.sh
before_script:
    - cd ..
    - git clone https://github.com/ethereum/tests.git
    - export ETHEREUM_TEST_PATH=$(pwd)/tests/
    - cd solidity
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$TRAVIS_BUILD_TYPE
script:
    # Build the code
    - cmake --build .

    # Run the tests
    #- $ETH_PATH --test -d /tmp/test
    #- while [ ! -S /tmp/test/geth.ipc ]; do sleep 2; done
    #- ./test/soltest --ipc /tmp/test/geth.ipc
    #- pkill eth

    # Generate Sphinx documentation if we're running on Trusty.
    #- $DOCS_COMMAND

    # Create ZIP
    - cd %APPVEYOR_BUILD_FOLDER%
    - zip solidity.zip %APPVEYOR_BUILD_FOLDER%/solc/%CONFIGURATION%/solc
    
#deploy:
#    provider: releases
#    api_key: "GITHUB OAUTH TOKEN"
#    file: cpp-ethereum.zip
#    skip_cleanup: true
#    on:
#        tags: true
