#------------------------------------------------------------------------------
# TravisCI configuration file for solidity.
#
# The documentation for solidity is hosted at:
#
# http://solidity.readthedocs.org
#
# TODO - Christian added a .travis.yml file to the development branch of
# solidity too, but for a different purpose - verifying the Sphinx
# documentation.  I have just overwritten that file for the purposes of this
# branch for right now, but will have to work out some means of
# consolidation.  Furthermore, there is another .travis.yml file which
# Christian has made which currently lives in the root of webthree-umbrella,
# but actually contains the automation for the Solidity Emscripten build,
# which will also need consolidating into here somehow.
#
# See https://github.com/ethereum/solidity/blob/develop/.travis.yml
# See https://github.com/ethereum/webthree-umbrella/blob/develop/.travis.yml
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=Debug
        - os: linux
          dist: trusty
          sudo: required
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
        - os: osx
          osx_image: xcode7.1
          env: TRAVIS_BUILD_TYPE=Debug
        - os: osx
          osx_image: xcode7.1
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=Debug
        - os: osx
          osx_image: xcode7.3
          env: TRAVIS_BUILD_TYPE=RelWithDebInfo
git:
    depth: 2
before_install:
    - ./setup.sh
before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$TRAVIS_BUILD_TYPE
script:
    - make
