#------------------------------------------------------------------------------
# TravisCI configuration file for solidity.
#
# The documentation for solidity is hosted at:
#
# http://solidity.readthedocs.org
#
# ------------------------------------------------------------------------------
# This file is part of solidity.
#
# solidity is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# solidity is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with solidity.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2016 solidity contributors.
#------------------------------------------------------------------------------

language: cpp
branches:
    # We need to whitelist the branches which we want to have "push" automation,
    # this includes tags (which are treated as branches by travis).
    # Pull request automation is not constrained to this set of branches.
    only:
        - develop
        - release
        - /^v[0-9]/

env:
    global:
        - ENCRYPTION_LABEL="6d4541b72666"
        - TRAVIS_BUILD_TYPE=RelWithDebInfo
        - TRAVIS_DOCS=Off
        - TRAVIS_EMSCRIPTEN=Off
        - TRAVIS_INSTALL_DEPS=On
        - TRAVIS_RELEASE=On
        - TRAVIS_TESTS=On
        - USE_DOCKER=Off
        - DOCKER_RELEASE=Off
        - DOCKER_OS=

matrix:
    include:
        # Ubuntu 14.04 LTS "Trusty Tahr" clang compile
      - os: linux
        dist: trusty 
        sudo: required
        services:
            - docker
        compiler:
          - clang
      # Ubuntu 14.04 LTS "Trusty Tahr" gcc compile
      - os: linux
        dist: trusty 
        sudo: required
        services:
            - docker
        compiler:
          - gcc
      # Docker image support for alpine native solc
      - os: linux
        dist: trusty 
        sudo: required
        services:
          - docker
        env: 
            - USE_DOCKER=On
            - DOCKER_OS=Alpine
            - TRAVIS_INSTALL_DEPS=Off
            - DOCKER_RELEASE=On
      - os: linux
        dist: trusty 
        sudo: required
        services:
          - docker
        env: 
            - USE_DOCKER=On
            - DOCKER_OS=Arch
            - TRAVIS_INSTALL_DEPS=Off
      - os: linux
        dist: trusty 
        sudo: required
        services:
          - docker
        env: 
            - USE_DOCKER=On
            - DOCKER_OS=Xenial
            - TRAVIS_INSTALL_DEPS=Off
      - os: linux
        dist: trusty 
        sudo: required
        services:
          - docker
        env: 
            - USE_DOCKER=On
            - DOCKER_OS=Fedora
            - TRAVIS_INSTALL_DEPS=Off
      - os: linux
        dist: trusty 
        sudo: required
        services:
          - docker
        env: 
            - USE_DOCKER=On
            - DOCKER_OS=Jessie
            - TRAVIS_INSTALL_DEPS=Off
        # Documentation target, which generates documentation using Phoenix / ReadTheDocs.
      - os: linux
        dist: trusty
        sudo: required
        env:
            - TRAVIS_DOCS=On
            - TRAVIS_RELEASE=Off
            - TRAVIS_TESTS=Off
        # Emscripten target, which compiles 'solc' to javascript and uploads the resulting .js
        # files to https://github.com/ethereum/solc-bin.  These binaries are used in Browser-Solidity
        # and in other Ethereum web-based development contexts.
      - os: linux
        dist: trusty
        sudo: required
        compiler: gcc
        node_js: stable
        services:
            - docker
        before_install:
            - docker pull trzeci/emscripten:sdk-tag-1.35.4-64bit
        env:
            - TRAVIS_EMSCRIPTEN=On
            - TRAVIS_INSTALL_DEPS=Off
            - TRAVIS_RELEASE=Off
            - TRAVIS_TESTS=Off
        # OS X images (assumes clang)

        # Yosemite
      - os: osx
        osx_image: xcode6.4
        services:
            - docker
        # El Capitan
      - os: osx
        osx_image: xcode7.3
        services:
            - docker
      - os: osx
        osx_image: xcode8
        services:
            - docker
        # Sierra
      - os: osx
        osx_image: xcode8.1
        services:
            - docker
      - os: osx
        osx_image: xcode8.2
        services:
            - docker
git:
    depth: 2

cache:
    ccache: true
    directories:
        - boost_1_57_0
        - build
        - $HOME/.local

install:
    - test $TRAVIS_INSTALL_DEPS != On || ./scripts/travis/travis_install_deps.sh
    - echo -n "$TRAVIS_COMMIT" > commit_hash.txt
before_script:
    - test $TRAVIS_EMSCRIPTEN != On || ./scripts/travis/build_emscripten.sh
    - test $TRAVIS_RELEASE != On || 
      && ./scripts/release.sh $ZIP_SUFFIX
      && ./scripts/create_source_tarball.sh )
script:
    - test $TRAVIS_DOCS != On || ./scripts/docs.sh
    - test $TRAVIS_TESTS != On || (cd $TRAVIS_BUILD_DIR && ./scripts/tests.sh)

deploy:
    # This is the deploy target for the Emscripten build.
    # It publishes the JS file which was compiled as part of the earlier 'build_emscripten.sh'
    # step to https://github.com/ethereum/solc-bin/tree/gh-pages/bin.
    # Both the build and deploy steps for Emscripten are only run within the Ubuntu
    # configurations (not for macOS).  That is controlled by conditionals within the bash
    # scripts because TravisCI doesn't provide much in the way of conditional logic.
    - provider: script
      script: test $TRAVIS_EMSCRIPTEN != On || scripts/release_emscripten.sh
      skip_cleanup: true
      on:
          branch:
            - develop
            - release

    # This is the deploy target for the native build (Linux and macOS)
    # which generates ZIPs per commit and the source tarball.
    #
    # This runs for each tag that is created and adds the corresponding files.
    - provider: releases
      api_key:
          secure: PWH37xVBCF0XiSjl+eH7XIdkrfxZXjzvqF4PiBOnD3VnFz+odrdnIwBmCeBYTHTWF8efpp8fmzWJk2UVq1JcpyZiC+SVxO8dx91W2ia1a+wKrEQuDgkUrZBkl5IQNCv0QS81DDQhliyZEaYh8wHO/7RReyMpGpw2U2u85WkFiZ+LdlHEZPfzUeh9lxQ9n8qwFL8Rja+Q05d4cQ8zaVEtofJJT4T6DUWhc3TzuxDYxOmjwg37rC9CkGSLn6VadSh8b3j5R0SZupFsAEvBL/imBLP9r9ewoo7o4p6By3jwiIgH9yNg7LM618xbffcNaYF/KtLBi9uPHfqF7hRD4PlECz+D0PR78nQItOX5HKm1QMg5kCnghRVCA0IVjpV5fiYQnMLM7dCRv34I5b3zLpa69wQ/GLYB2FViqNUfvPeiZTEeIJ2OmATlFx8AH2JoqpY1XJknWb35+vMfa8LSiJJW++SLWeV+ncC92hrvyZ1cy3trepRRZIfyYepxHifnfdWMkddQUJk5b2WS5Fy/TJLZNPeombnpvRhUC38dsYItarKeXTc6k4oADCEDZ2rgGIcEiqRxXV11Y5xHJekLDWzUs+YJNcCuL4pnAP//LOnbnH2w9rLpwhQYSl0anCd097NivAXQJXO2JI/byIYz1kiCVQWnW6EM8+72mLOklf/Qr8k=

      overwrite: true
      file_glob: true
      file:
          - $TRAVIS_BUILD_DIR/solidity*.zip
          - $TRAVIS_BUILD_DIR/solidity*tar.gz
      skip_cleanup: true
      on:
          all_branches: true
          tags: true
          condition: $TRAVIS_RELEASE == On