#------------------------------------------------------------------------------
# TravisCI configuration file for solidity.
#
# The documentation for solidity is hosted at:
#
# http://solidity.readthedocs.org
#
# TODO - Merge with .travis.yml file which currently lives in the root of
# webthree-umbrella, but actually contains the automation for the Solidity
# Emscripten build, which will also need consolidating into here somehow.
#
# See https://github.com/ethereum/webthree-umbrella/blob/develop/.travis.yml
#
# ------------------------------------------------------------------------------
# This file is part of cpp-ethereum.
#
# cpp-ethereum is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cpp-ethereum is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cpp-ethereum.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
branches:
    only:
        - develop
        - release
        - standalone
    except:
        - /develop-v[0-9]/
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          compiler: gcc
          services:
              - docker
          before_install:
              - docker pull trzeci/emscripten:sdk-tag-1.35.4-64bit
          env:
              - TRAVIS_BUILD_TYPE=RelWithDebInfo
              - ZIP_SUFFIX=ubuntu-trusty
        - os: osx
          osx_image: beta-xcode6.2
          env:
              - TRAVIS_BUILD_TYPE=RelWithDebInfo
              - ZIP_SUFFIX=osx-mavericks
        - os: osx
          osx_image: xcode7.1
          env:
              - TRAVIS_BUILD_TYPE=RelWithDebInfo
              - ZIP_SUFFIX=osx-yosemite
        - os: osx
          osx_image: xcode7.3
          env:
              # The use of Debug config here ONLY for El Capitan is a workaround for "The Heisenbug"
              # See https://github.com/ethereum/webthree-umbrella/issues/565
              - TRAVIS_BUILD_TYPE=Debug
              - ZIP_SUFFIX=osx-elcapitan
git:
    depth: 2
cache:
    ccache: false
    directories:
        - boost_1_57_0
        - jsoncpp
        - cryptopp
install:
    - ./scripts/install_deps.sh
before_script:
    - mkdir -p build
      && cd build
      && cmake .. -DCMAKE_BUILD_TYPE=$TRAVIS_BUILD_TYPE
      && make -j2
      && cd ..
      && ./scripts/release.sh $ZIP_SUFFIX
    - cd $TRAVIS_BUILD_DIR && ./scripts/build_emscripten.sh
script:
    - ./scripts/tests.sh
after_success:
    - ./scripts/docs.sh
env:
    global:
        - ENCRYPTION_LABEL="296c219a3f41"
deploy:
    provider: releases
    api_key:
        secure: mGeDrlCbhPNQVqrk5wSqFZe/7C5HUIBWcZECJcFrEldN6ELj3a8mhDX9EWebidyFmZsf3ipKVMycJtXZHlH2kVZ0nZdRulq4bYhLiUFRaFQCHMW35dml5mxO/FPp+jhhZaylDUx+cI6AULbj8DvNFqSCfjx8qimRhJjRY4JHeG71N6g5+LU2/dA01D4Y97BUbQ5dYcmEyuEsriSpXOElIQIIv3+Q6MJNnLzxUA6EXsp4Qt3Qf3R1+EkI/RWOPbQsddpFNJBcBNOscCUFSZV3+ZK9E2RyHbPaL+Da4aJKVpgD7X1TFudq4PClMUTkg8CuJh/kvy9wkpaWyYHbLGQqu1vQ+NQ+vlTAKf8U+1xhC1IkX6nA+g4TlRksZRltRhpkBPnFoaQQGjD9eYyT1V/Htrn8Y/VGbYPBVa0GcEYXG5pDCBPz91RBpYwDcyUg9DEPNI6zYfQY8jA8xqtFwPX79Y22MDXIKhBskK00geuzh7Npy5Rnh4fLqVKMlffvYx3kwp444EFWtQ5jxbRCym2Th6EldkOM8Kble1JvixQtVb4s+DpTuwHCTrXZhwMuJpmwgRx52zyIsGrBPF3MOmdlwl+l0TD8UEJXt0JM1XSF1AROyYwXKDZQ9Qt4sd9ZKSWWaLJMEJf4kkZWYgTEI/FhOWlfshQCt8Z9S9r4fq2ywoo=
    file: $TRAVIS_BUILD_DIR/solidity-develop-$ZIP_SUFFIX.zip
    skip_cleanup: true
    on:
        repo: bobsummerwill/solidity
        branch: standalone
#deploy:
#    provider: script
#    script: scripts/travis-emscripten/publish_binary.sh
#    skip_cleanup: true
#    on:
#        branch: develop
