#------------------------------------------------------------------------------
# Appveyor configuration file for solidity.
#
# The documentation for solidity is hosted at:
#
# http://solidity.readthedocs.org
#
# TODO - Tests currently disabled, because Tests-over-IPC code is using UNIX
# sockets unconditionally at the time of writing.
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

version: 0.3.5.{build}
skip_tags: true
os: Visual Studio 2015
configuration:
    - Debug
install:
    - git submodule update --init --recursive
    - install_deps.bat
    - set ETHEREUM_DEPS_PATH=%APPVEYOR_BUILD_FOLDER%\deps\install
before_build:
    - cd ..
    - git clone https://github.com/ethereum/tests.git
    - set ETHEREUM_TEST_PATH=%APPVEYOR_BUILD_FOLDER%\..\tests
    - cd %APPVEYOR_BUILD_FOLDER%
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64" .. -DTESTS=Off
build_script:
    # Build code
    - msbuild solidity.sln /p:Configuration=%CONFIGURATION% /m:%NUMBER_OF_PROCESSORS%

    # Create ZIP
    - cd %APPVEYOR_BUILD_FOLDER%
    - 7z a solidity.zip %APPVEYOR_BUILD_FOLDER%\build\solc\%CONFIGURATION%\solc.exe %APPVEYOR_BUILD_FOLDER%\build\solc\%CONFIGURATION%\soltest.exe "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\msvc*.dll"

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%\build\test\%CONFIGURATION%
    - copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\msvc*.dll" .
#    - eth.exe --test -d %TMP%/test
#    - soltest.exe --ipc /tmp/test/geth.ipc
#    - pkill eth
    
artifacts:
    - path: solidity.zip
      name: solidity-zip
deploy:
    release: solidity-appveyor-v$(appveyor_build_version)
    description: 'Automated Appveyor release of solidity'
    provider: GitHub
    auth_token:
        secure: yukM9mHUbzuZSS5WSBLKSW0yGJerJEqAXkFhDhSHBBcKJE7GAryjQsdO9Kxh3yRv
    artifact: solidity-zip
    on:
        branch: standalone_prior_to_splat
