#------------------------------------------------------------------------------
# Appveyor configuration file for solidity.
#
# The documentation for solidity is hosted at:
#
# http://solidity.readthedocs.org
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

install:
    - cd extdep && getstuff.bat > NUL
before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 12 2013 Win64" ..
build:
    project: build/solidity.sln
