name: Find stale issues
inputs:
  github_token:
    description: 'GitHub API token'
    required: true
  inactivity_period:
    description: "The inactivity period in days"
    required: false
    type: number
  repo:
    description: "The target repository"
    required: false
    type: string
    default: "${{ github.repository_owner }}/${{ github.event.repository.name }}"
outputs:
  result:
    description: "List of issue URLs. The list is in a format suitable for iteration with a shell loop, i.e. escaped and separated with whitespace."
    value: ${{ steps.found_issues.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Get a concrete cut-off date matching the inactivity period
      id: date
      shell: bash
      run: |
        inactivity_period_date=$(date --date "${{ inputs.inactivity_period }} days ago" --utc +"%Y-%m-%dT%H:%M:%SZ")
        echo "inactivity_period=$inactivity_period_date" >> $GITHUB_OUTPUT

    - name: Get inactive open issues
      id: stale_issues
      if: ${{ success() }}
      uses: ethereum/solidity/.github/actions/query_issues@develop
      with:
        github_token: ${{ inputs.github_token }}
        query: 'repo:${{ inputs.repo }} is:issue is:open updated:<${{ steps.date.outputs.inactivity_period }}'

    - name: Collect query result
      id: found_issues
      if: ${{ success() }}
      shell: bash
      run: |
        filter_result=$(
          jq \
            --raw-output \
            --null-input \
            --argjson result '${{ steps.stale_issues.outputs.query_result }}' \
            '[$result.data.search.nodes[].url] | @sh' \
          | tr --delete \'
        )
        echo "result=$filter_result" >> $GITHUB_OUTPUT
