# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Labeler
on: [pull_request]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_DOCKER_REPOSITORY: docker.pkg.github.com/${{ github.repository }}
      IMAGE_NAME: ubuntu2004.clang

    runs-on: ubuntu-latest

    steps:
    - uses: futuratrepadeira/changed-files@v3.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pattern: '^.*\.(Dockerfile).*'
      
    - uses: actions/checkout@v2

    - name: Build image
      run: |
        echo "files_created: ${files_created}"
        echo "files_updated: ${files_updated}"
        echo "files_deleted: ${files_deleted}"
